In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data sources:
- https://openjustice.doj.ca.gov/data
- https://datacenter.aecf.org/data/customreports/1/103

In [2]:
felony = pd.read_csv("data/felony_data.csv")
felony.head(10)

                RACE_DESC  COUNT OF FELONIES  % OF FELONIES  YEAR
0  Asian/Pacific Islander               1048       2.504601  2012
1                   Other               1266       3.025596  2012
2                   White               7904      18.889659  2012
3                   Black               9397      22.457759  2012
4                Hispanic              22228      53.122386  2012
5  Asian/Pacific Islander                928       2.476384  2013
6                   Other               1005       2.681859  2013
7                   White               6757      18.031168  2013
8                   Black               8830      23.563004  2013
9                Hispanic              19954      53.247585  2013

In [3]:
felony.dtypes

RACE_DESC                str
COUNT OF FELONIES      int64
% OF FELONIES        float64
YEAR                   int64
dtype: object

In [4]:
children = pd.read_csv("data/child_demographics_clean.csv")
children.head(10)

                RACE_DESC  Year  Population Count  % of Population
0  Asian/Pacific Islander  2019           4065560         5.562503
1  Asian/Pacific Islander  2021           4171342         5.664553
2  Asian/Pacific Islander  2022           4239493         5.775625
3  Asian/Pacific Islander  2023           4325923         5.904213
4  Asian/Pacific Islander  2024           4434461         6.063580
5                   Black  2019          10034057        13.728607
6                   Black  2021          10162116        13.799838
7                   Black  2022          10156681        13.836839
8                   Black  2023          10151595        13.855350
9                   Black  2024          10138247        13.862806

In [5]:
children.dtypes

RACE_DESC               str
Year                  int64
Population Count      int64
% of Population     float64
dtype: object

In [11]:
df = felony.merge(
    children,
    left_on=["RACE_DESC","YEAR"],
    right_on=["RACE_DESC","Year"],
    how="right"
)

df = df.drop(columns=["YEAR"])
df.sort_values(by=["Year", "Population Count"], inplace=True)
df.head()

,RACE_DESC,COUNT OF FELONIES,% OF FELONIES,Year,Population Count,% of Population
15,Other,933,4.162577,2019,3912572,5.353185
0,Asian/Pacific Islander,472,2.105827,2019,4065560,5.562503
5,Black,5795,25.854377,2019,10034057,13.728607
10,Hispanic,11889,53.042741,2019,18588264,25.432482
20,White,3325,14.834478,2019,36488222,49.923223

**Null Hypothesis**
The proportion of Hispanic minors in the population is proportionate/equal to the occurence of felony cases that are Hispanic.

**Alternative Hypothesis**
The proportion of Hispanic minors in the population is disproportionate to the occurence of felony cases that are Hispanic.
Specifically, the % of felony cases that are Hispanic is GREATER than the % of Hispanic minors.